### ISSUE TITLE
Random swithing of pages because collision issue

### ISSUE THREAD

**Issue by IvailoBurov** [miskatonicstudio/interactive-book-godot#22]
I looked at the sample scene where switching pages is quite random. The reason is that the ray can collide accidentally with nearby collision boxes. Maybe if you use a player camera with a variable angle, this will not be a problem, but with the  book camera aimed at 90 degrees to the collision boxes is. Here is a simple method that I just tested to avoid this issue:

```
func _on_StaticBody_input_event(camera, event, position, normal, shape_idx):
	
if event is InputEventMouseButton :
		if(shape_idx == 0):
			turn_left()
		if(shape_idx == 1):
			turn_right()
```

**Comment by miskatonicstudio** [comment]
Hi! Thanks for your input! :) 

The thing with Interactive Book project is that it started as a "normal" 3D project, but I've made experiments with VR as well. I haven't touched this code for a while, but if I remember correctly, in VR you are supposed to move the camera, and in standard 3D you should be using arrow keys instead (left and right). I'm afraid the arrow keys are disabled in VR for some reason :(

So, to fix this properly, I need to provide a nice default 3D scene, probably the "normal" one, but make it clear that VR is also an option (or make a switch in the app itself). I will have to think this through :P 

Thank you for pointing this out, I have neglected this project a bit, this might motivate me to polish it a bit more :D

**Comment by IvailoBurov** [comment]
I think that 3D book will be useful for education fragments. I will use it directly at current stage, however implementation as interactive item is a good idea. Also in-game camera is good idea too: https://usagishima.net/2021/03/18/devlog-1-in-game-camera-and-photo-album/
I tried it, however not like interactive object since there are not any option for dropping items from inventory.

**Comment by miskatonicstudio** [comment]
Hi! I realized that my local copy of this repo has a lot of experimental changes, so I checked the clean version :smile:  The default scene starts in VR mode, and if it runs on a desktop computer, then the switching of pages is, indeed, random. I'm afraid checking the collision shape ID would not help here, because the raycast that aims directly ahead will still randomly pick one of them (each area has only one collision shape). Until I figure out how to clean up this project, I would suggest enabling the keyboard in this scene:

```
+       if Input.is_action_just_pressed("ui_left"):
+               turn_left()
+       if Input.is_action_just_pressed("ui_right"):
+               turn_right()
```

Of course, this will not work in VR (at least not on Android, where I test it :stuck_out_tongue: ) but it would make the pages work in desktop mode for now. Do you think this solution would solve your problem?

**Comment by miskatonicstudio** [comment]
I've added that code to the repo, I hope it will help you :)  If you have other suggestions for improvements, please let me know!
